### ISSUE TITLE
Error 'No org-babel-execute function for jupyter-python!' with (GUI version emacs with Mac).  

### ISSUE THREAD

**Issue by tlkahn** [nnicandro/emacs-jupyter#168]
As title. But in console, everything works fine...

**Comment by tlkahn** [comment]
I have put the lines as below:

```
(add-to-list 'org-src-lang-modes '("jupyter" . python))

(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)
   (js . t)
   (ruby . t)
   (C .t)
   (shell .t)
   (mathematica .t)
   (clojure .t)
   (R .t)
   (jupyter . t)
   ;; other languages..
   ))

(org-babel-jupyter-override-src-block "python")
```

**Comment by dzop** [comment]
Did you have any messages in the `*Messages*` buffer that start like `Error retrieving kernelspecs`?

**Comment by zeneofa** [comment]
Hi, I have the same issue, and yes the `Error retrieving kernelspecs` entry appears in the `*Messages*` buffer. 

When I run `jupyter-run-repl` I get `Can’t obtain kernelspecs from jupyter shell command`. Jupyter is installed in an anaconda environment, where the environment has been activated and emacs started from the same shell.

I am using emacs 26.1 on Windows, I installed the package using the spacemacs-layer `https://github.com/benneti/spacemacs-jupyter`, with spacemacs version 0.3.0.0. And my .spacemacs file does contain:

```
 (with-eval-after-load 'org
    (org-babel-do-load-languages
     'org-babel-load-languages
     '(
       (python . t)
       (R . t)
       (jupyter . t)
       )
     )
    )
  )
```
The code in org-babel I am trying to run is:

```
#+begin_src jupyter-python :session py
x = 'foo'
y = 'bar'
x + ' ' + y
#end_src
```
I have tried to use `jupyter-python3`, which matches my kernel name.  Activating the kernel and then pointing to the json file with the `:session` header also doesn't work. 

Any advice?

**Comment by dzop** [comment]
What does `(shell-command-to-string "jupyter kernelspec list")` return?

**Comment by zeneofa** [comment]
I get the long error below. Which is caused by the conda environment not being activated. 

```
_cffi_ext.c
C:\Users\jq2\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(213): fatal error C1083: Cannot open include file: 'sys/un.h': No such file or directory
Traceback (most recent call last):
  File "C:\Users\jq2\AppData\Local\Continuum\anaconda3\Scripts\jupyter-kernelspec-script.py", line 5, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "C:\Users\jq2\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\jq2\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
    import zmq
  File "C:\Users\jq2\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\jq2\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\jq2\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\jq2\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\jq2\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\jq2\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
```

As the following gives the expected output `  (shell-command-to-string "C:\\Users\\jq2\\AppData\\Local\\Continuum\\anaconda3\\Scripts\\activate.bat & jupyter kernelspec list")
`
It appears that the environment from which emacs was called isn't inherited :( I have no idea how to make sure that the "activate" command is called, such that jupyter (and for that matter emacs in general) is called properly.

**Comment by dzop** [comment]
I don't use Windows, but maybe try a batch script with the following lines

```
activate.bat
runemacs
```

and call that to launch Emacs. I don't know how your launching Emacs, but I believe most of the time it is launched in a fresh `cmd.exe` process **without** any inherited environment. I remember running into issues like this when I was trying to get the appveyor tests working for this package, but unfortunately I don't remember much of the details.

**Comment by zeneofa** [comment]
the activate/runemacs is exactly what I run beforehand (though I use a python script, and not a batch script). I assumed that it was using a clean `cmd.exe` environment, I am therefore looking into `https://github.com/necaris/conda.el` to see that can work. At the moment it doesn't quite fit the recommended conda activation procedure for windows, but will see what I can do with a bit of tinkering. It also doesn't seem to activate the base environment, only those that have been created by the user. If didn't have to use windows this would be so much easier...

**Comment by dzop** [comment]
I just remembered the details. Since your using a `python` script to activate Emacs within the conda environment are you using something like `os.execve` to start the Emacs process, e.g. with `subprocess.call` or similar (not 100% sure that's what `subprocess.call` is using behind the scenes)?

If you are, then you are probably running into https://bugs.python.org/issue9148. Basically, `execve` like commands all start new processes on Windows instead of forking the current one so they all start in a fresh environment.

**Comment by zeneofa** [comment]
I have managed to get further with the above, sorry had to focus on other projects for a bit. I found the conda elpa package: `https://github.com/necaris/conda.el` . I then wrote a spacemacs layer around this, which allowed me to activate the base conda environment from within emacs. Jupyter now detects the kernels. However, I am unable to start the kernels as I get the following error when running `jupyter-run-repl`:
```
helm-M-x: Modules are not supported
```

I have no idea how to proceed from here. Any advice?

**Comment by dzop** [comment]
Looks like your Emacs was not built with module support. That is the case if the variable `module-file-suffix` is nil. I don't think Emacs comes with module support by default, but if you are using an MSYS2 shell you can get an Emacs with module support with 
`pacman --needed -S mingw-w64-x86_64-emacs mingw-w64-x86_64-libxml2 mingw-w64-x86_64-libjpeg-turbo`. You may not need the latter two dependencies.

**Comment by zeneofa** [comment]
I managed to get an emacs on windows that is compiled with module support: (https://github.com/m-parashar/emax64).  My current issue is that when executing `jupyter-run-repl` I get
```
Check for compatible module binary to download? (y or n) y
Downloading https://github.com/dzop/emacs-zmq/releases/download/v0.10.10/emacs-zmq-x86_64-w64-mingw32.tar.gz
Verifying sha256 signature of emacs-zmq-x86_64-w64-mingw32.tar.gz
helm-M-x: Signature did not match content
```

Should I ask this issue on that repo?

**Comment by dzop** [comment]
Do you still have the signature issue? I think it would be better to open a new issue over at emacs-zmq.

**Comment by dzop** [comment]
@tlkahn Where you able to figure out your problem? If you get the `No org-babel-execute function for jupyter-python` error it usually indicates that the kernelspecs could not be found on your system. Can you show the result of evaluating 
`(jupyter-available-kernelspecs)`? If the result is anything other than `nil`, the issue probably lies elsewhere.

**Comment by LiShi2269** [comment]
> What does `(shell-command-to-string "jupyter kernelspec list")` return?
> 
> If it doesn't fail and returns the kernelspecs, then it might just be that by the time the `ob-jupyter` file is loaded (which is when we try to get the kernelspecs) the paths used by Emacs to search for shell programs aren't setup yet. If this is the case you should be able to call `(org-babel-jupyter-aliases-from-kernelspecs)` to get everything working again.
> 
> The `ob-jupyter` file is loaded whenever that `org-babel-do-load-languages` call is evaluated so you should check to see that `(executable-find "jupyter")` returns a valid path right before the call.

this is helpful , thank you !
