### ISSUE TITLE
#+begin_export latex

### ISSUE THREAD

**Issue by benneti** [nnicandro/emacs-jupyter#218]
Sometimes if a source block returns latex equations it gets wrapped in an export block.
Is there a reason for this (this is the case for results raw when using SymPy.jl)?
(and can I deactivate it somehow, because at least for me this disables preview latex which is a bit annoying).

Best,
Benedikt

**Comment by dzop** [comment]
Can you give an example src-block where this happens? Latex fragments are potentially wrapped in export blocks when `:results raw` is **not** specified. If you specify `:results raw`, the latex fragments should be inserted directly in the buffer without being wrapped.

The intention of [this](https://github.com/dzop/emacs-jupyter/blob/1546a72f570c7d3a6376d211d27002b2b11ddb40/jupyter-org-client.el#L1511) function is to display a preview of a newly inserted fragment if the variable `jupyter-org-toggle-latex` is non-nil, but it looks like it doesn't work if there aren't any previously previewed latex fragment before the point where the new fragment is being inserted. You may also want to check your value of `jupyter-org-toggle-latex`.

**Comment by benneti** [comment]
```julia
#+BEGIN_SRC jupyter-julia  :results raw
using SymPy
expand(exp(-im*2*sympy.pi/3), complex=true)
#+END_SRC

#+RESULTS:
:RESULTS:
: ┌ Info: Precompiling SymPy [24249f21-da20-56a4-8eb1-6a02cf4ae2e6]
: └ @ Base loading.jl:1273
\begin{equation*}- \frac{1}{2} - \frac{\sqrt{3} i}{2}\end{equation*}
:END:

#+BEGIN_SRC jupyter-julia  :results drawer raw
expand(exp(-im*2*sympy.pi/3), complex=true)
#+END_SRC

#+RESULTS:
:RESULTS:
\begin{equation*}- \frac{1}{2} - \frac{\sqrt{3} i}{2}\end{equation*}
:END:

#+BEGIN_SRC jupyter-julia  :results raw drawer
expand(exp(-im*2*sympy.pi/3), complex=true)
#+END_SRC

#+RESULTS:
:results:
#+begin_export latex
\begin{equation*}- \frac{1}{2} - \frac{\sqrt{3} i}{2}\end{equation*}
#+end_export
:end:
```

I realised that by dropping the drawer argument or changing the order I can get what I want.
Now I am not sure anymore whether it was my fault or not for keeping the drawer in while adding raw...

**Comment by vale981** [comment]
I am having the same problem with python. For me `:results drawer raw` does not even work.

**Comment by vale981** [comment]
LOL,
just add `:pandoc t` as a header arg :)
