### ISSUE TITLE
Document procedure for running tests locally

### ISSUE THREAD

**Issue by non-Jedi** [nnicandro/emacs-jupyter#239]
Apologies if this is a really obvious answer, but I've been utterly unable to figure out how to run the tests for this package locally. Would you mind adding a heading in the README explaining how to do so (what packages need to be installed and an `emacs --batch` command)?

**Comment by non-Jedi** [comment]
It was really obvious. The Makefile has a test target. Just need to iron out getting cask installed locally.

**Comment by dzop** [comment]
Sorry, I thought I had documented that.  In the project directory, run `make dev` once after installing Cask and then `make test` to run all tests or something like `make test TAGS=org` to run a subset.
