### ISSUE TITLE
Running default with python2

### ISSUE THREAD

**Issue by chupy35** [nnicandro/emacs-jupyter#243]
By default runs with the kernel in python2, how can i make python3 the default?

**Comment by fleimgruber** [comment]
Please have a look into the [docs](https://github.com/nnicandro/emacs-jupyter#org-mode-source-blocks), esp. `org-babel-default-header-args:jupyter-python` and the `:kernel` part. Also check which kernels are available to emacs-jupyter on your system via `(jupyter-available-kernelspecs)`.
