### ISSUE TITLE
Add 'autoscroll' to *jupyter-output* buffer

### ISSUE THREAD

**Issue by djthorne** [nnicandro/emacs-jupyter#244]
At the moment updates to the *jupyter-output* buffer bring the point to the top. It is often desirable that the new output that was appended to the bottom is immediately viewable ('autoscrolling' behavior which keeps the point at the end of the buffer). This is a small enhancement that would be very useful (particularly when using interactive debugging). I would  make an attempt if someone could give me some advice/point me in the right direction.

**Comment by nnicandro** [comment]
Thanks for the idea. It was simple enough that I went ahead and implemented it myself in 
b87ecf0. Let me know if you were meaning something else.
