### ISSUE TITLE
does emacs-jupyter support ihaskell?

### ISSUE THREAD

**Issue by zeta-00** [nnicandro/emacs-jupyter#259]
hello there,
i installed ihaskell and got it to work with emacs-ipython-notebook, but i have not been able to get the ihaskell auto-completion to work inside of a .ipynb file, that's why i ended up switching to atom and installed the hydrogen package, with atom's hydrogen package, i just need to connect the ihaskell kernel, and everything works out-of-the-box.

so does ihaskell work in emacs-jupyter? if yes, then, can emacs-jupyter be configured like atom's hydrogen package, so that ihaskell can work out-of-the-box?

**Comment by fleimgruber** [comment]
How did you try to configure and connect to the ihaskell kernel from emacs-jupyter? Is the ihaskell kernel visible to emacs-jupyter via `(jupyter-available-kernelspecs)`? You should then be able to start a kernel and connect to it via `jupyter-run-repl`.

**Comment by nnicandro** [comment]
Yes there are people that do use the Haskell kernel with `emacs-jupyter` and it appears to work out of the box. You just need to ensure that the kernel is available in your Jupyter installation as @fleimgruber mentioned.

Please open up a new issue if you run into problems with getting it to work.
