### ISSUE TITLE
jupyter-current-client and org-mode code blocks

### ISSUE THREAD

**Issue by Salompas** [nnicandro/emacs-jupyter#266]
Consider a code block:
```
#+BEGIN_SRC jupyter-R :session r :results output :async yes
print("Hello World!")
#+END_SRC
```
Using `org-edit-special` (usually assigned to `C-'`) opens the code block in a buffer, starts a jupyter R kernel, and associates the buffer with the kernel (not exactly sure on this). In the buffer we can use `jupyter-eval-line-or-region` and the code runs.

However, if we do not use `org-edit-special` (we are still in the org-mode buffer), and then use `jupyter-eval-line-or-region`, then we get the error `Wrong type argument: "Not a valid client", nil, jupyter-current-client`.

Is it possible to make emacs-jupyter work with code blocks in org-mode without having to use `C-'`?

Thanks!

Edit 1: It is interesting that other functions work in org-mode, like `jupyter-inspect-at-point`.

**Comment by dangom** [comment]
It should be possible to implement your desired behaviour by having jupyter-eval-line-or-region grab the underlying jupyter-current-client from the src block, yet why not simply evaluating the src-block with `C-c C-c`?

**Comment by wuqui** [comment]
I agree, this would be great for several reasons. 

Very often I want to explore and just evaluate part of a source block, e.g. to inspect a variable. Just having the REPL as a second window and not having to open up dedicated `org-edit-special` buffers would be a big advantage.

Besides, this would be particularly important for using `lsp-mode` and it's `lsp-org`  function for the org buffer.

**Comment by dangom** [comment]
Have you had any success in using lsp-mode and lsp-org with emacs-jupyter? Would love to hear your experiences.

**Comment by wuqui** [comment]
Yes, I'm having some success. There are still a couple of things that don't work for me, unfortunately.  I've said a couple of things in a thread over at `lsp`: https://github.com/emacs-lsp/lsp-mode/issues/2004#issue-674444410

I have to say that I'm not an expert on all of the moving parts involved, so the problem might be on my side. I'd be really happy if other people give this a try too.

**Comment by ngharrison** [comment]
To the original issue, I've found a workaround for now:

1. Put the org-mode buffer into the mode of the language you are using (I've used python-mode and julia-mode)
2. Use `jupyter-repl-associate-buffer` and pick the kernel you want
3. Put the buffer back into org-mode

This allows me to still run code blocks as well as pass snippets to the repl using `jupyter-eval-line-or-region`.

**Comment by nnicandro** [comment]
With regards to the original issue:

There is already a keybinding `C-x C-e` that lets you evaluate the current line or region of a source block without having to go to the edit buffer. That keybinding is defined like this

`(jupyter-org-define-key (kbd "C-x C-e") #'jupyter-eval-line-or-region)`

The special part is that `jupyter-org-define-key` will wrap the bound command, in this case `jupyter-eval-line-or-region`, in a macro that ensures `jupyter-current-client` is bound to the client of the source block under `point`. The final command is just something like

```emacs-lisp
(defun final-command ()
  (interactive)
  (jupyter-org-with-src-block-client
   (call-interactively #'jupyter-eval-line-or-region))
```

So you can either use `jupyter-org-define-key` or wrap your own commands with `jupyter-org-with-src-block-client` to get commands that work within code blocks in Org without going to the edit buffer.
