### ISSUE TITLE
:var from a :cache result is nil

### ISSUE THREAD

**Issue by mankoff** [nnicandro/emacs-jupyter#267]
Here is an MWE that works:

```Org
#+NAME: foo
#+BEGIN_SRC bash :results table drawer :cache no
echo 42
echo 24
#+END_SRC

#+RESULTS: foo
:results:
| 42 |
| 24 |
:end:

#+name: py
#+begin_src jupyter-python :var tbl=foo :session foo :cache yes :kernel foo 
tbl
#+end_src

#+RESULTS[b4609a2e215f2add550d31119eaf39006325dcf1]: py
|   |  0 |
|---+----|
| 0 | 42 |
| 1 | 24 |
```

Here is an MWE that fails. The only change is `:cache no` to `:cache yes` on the 2nd line.

```Org
#+NAME: foo
#+BEGIN_SRC bash :results table drawer :cache yes
echo 42
echo 24
#+END_SRC

#+RESULTS[c365bd1c41c7becd179bdb7bb4433da7007d0212]: foo
:results:
| 42 |
| 24 |
:end:

#+name: py
#+begin_src jupyter-python :var tbl=foo :session foo :cache yes :kernel foo 
tbl
#+end_src

#+RESULTS[3181f598175868dbeacd35e4c541f484234ce62c]: py
|   | 0 |
|---+---|
| 0 | n |
| 1 | i |
| 2 | l |

```

**Comment by nnicandro** [comment]
This is an issue on the `org-babel` side of things. If you change the `jupyter-python` block to the `python` block

```
#+begin_src python :var tbl=foo
return tbl
#+end_src
```

you get the same problem.

I found [this thread](https://lists.gnu.org/archive/html/emacs-orgmode/2018-09/msg00067.html) on the Org mailing list discussing this issue. No replies to it though.

I traced the problem back to `org-babel-read-element` not being able to read a drawer as a Lisp expression.

There is nothing on the `emacs-jupyter` side that can be done for this.
