### ISSUE TITLE
randomly spawns jupyter stdout / traceback windows?

### ISSUE THREAD

**Issue by matteha** [nnicandro/emacs-jupyter#279]
When I have my code on one side, and the REPL on the right side, and I send the code to the REPL (eval-region), sometimes the following buffers all pop up:

- jupyter stdout
- jupyter stderr
- jupyter traceback
-jupyter display 

with all the output as well. Is this a bug? Or is there a way to turn this off, to be able to only focus on the REPL buffer with all output? It seems to be related to code blocks, if code blocks are large these buffers are more likely to pop up? 

Fantastic package by the way!

**Comment by matteha** [comment]
Sorry didn't read carefully enough, fixed it with

(setq jupyter-eval-short-result-max-lines 0)

**Comment by xukai92** [comment]
I still have the same issue even after I do `(setq jupyter-eval-short-result-max-lines 0)`. Any idea why?
