### ISSUE TITLE
I wish this was in the readme

### ISSUE THREAD

**Issue by littlehome-eugene** [nnicandro/emacs-jupyter#283]
https://www.reddit.com/r/emacs/comments/b6f252/new_package_emacsjupyter/

> sorry, couple very n00b questions. I'm new to all jupyter, etc. 1) is there a way to get a list of view (like what I got in the browser)? in EIN, there is a list of notebooks function. 2) if I have an existing ipynb file, how to open it? I tried "jupyter-load-file" but it complains jupyter-kernel-client is nil
> 
> 
> 
> level 2
> nnican
> 1 point
> ·
> 11 months ago
> If you want to get a list of live kernels available behind a notebook server, you should use M-x jupyter-server-list-kernels. You can get a dired buffer of the files served behind a notebook server using something like M-x dired RET /jpy:localhost#8888:/ if the notebook server lives at http://localhost:8888.
> 
> You can't open ipynb files using emacs-jupyter at the moment, as mentioned in the README. So I would suggest you stick with EIN if you are mainly working with ipynb files. The main interface for emacs-jupyter is either the REPL or org-mode source blocks. jupyter-load-file means to send the contents of a file to a kernel for evaluation. I would like to do something with ipynb files in the future, but I don't know what the best way to go about it would be and there already is EIN...

**Comment by fleimgruber** [comment]
Which part(s) exactly do you want to see in the README? Please consider opening a PR with the information you would want to see there.
