### ISSUE TITLE
async v async

### ISSUE THREAD

**Issue by malb** [nnicandro/emacs-jupyter#294]
Hi, I'm not sure this belongs here, but here it goes. Starting emacs (28.1, nativecomp) with `emacs -q -l async-debug.el foo.org` where `async-debug.el`:

```emacs-lisp
(setq comp-deferred-compilation-deny-list '("jupyter-channel"
                                             ))
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")))

(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package jupyter)

(use-package ob
  :config (progn
            ;; load more languages for org-babel
            (org-babel-do-load-languages
             'org-babel-load-languages
             '((python . t)
               (shell . t)
               (jupyter . t)))          ; must be last

            (setq org-babel-default-header-args:sh    '((:results . "output replace"))
                  org-babel-default-header-args:bash  '((:results . "output replace"))
                  org-babel-default-header-args:shell '((:results . "output replace"))
                  org-babel-default-header-args:jupyter-python '((:async . "yes")
                                                                 (:session . "py")
                                                                 (:kernel . "sagemath")))))

(use-package ob-async
  :config (setq ob-async-no-async-languages-alist '("jupyter-python" "jupyter-julia")))
```

and `foo.org`:

```org
#+begin_src jupyter-python :kernel sagemath
sqrt(1.2)
#+end_src

#+RESULTS:
: 1.09544511501033

#+begin_src shell :async
echo foo
#+end_src

#+RESULTS:
: 51f1e558264b519a207d219f5921b308
```

I'm getting 
```
error in process sentinel: async-when-done: Invalid read syntax: "#"
error in process sentinel: Invalid read syntax: "#"
```
when I evaluate the second block. But after killing the jupyter repl buffer evaluating that second block succeeds.

**Comment by timlod** [comment]
I've recently run into the same error (emacs 27.1) when trying to use normal `python` with org-babel - I think it also only happened when I also try to accomodate `jupyter-python` blocks in the same org file.

**Comment by johanfforsberg** [comment]
I just ran into what looks like the same problem, and it seems to be related to the `ob-async` package. The instructions in the README mention that you might need to exempt jupyter languages like so:

```(setq ob-async-no-async-languages-alist '("jupyter-python" "jupyter-julia")```

When I did that correctly it seems to work OK (only tried it with jupyter-python though). Obviously, uninstalling `ob-async` also worked, but I want it for other stuff.

**Comment by malb** [comment]
Hi, I have that line in my config, see above, and that worked with 26.2, but now with 28 (nativecomp) it doesn't, any longer.

**Comment by johanfforsberg** [comment]
Yes, I should have read your issue more closely, sorry. I also tried with the nativecomp branch but had some other issues there with this package. I see you are setting `comp-deferred-compilation-black-list` to avoid that, I didn't know about that!

One thing you could try is to move the `ob-async` `:config` stuff into `:init` instead (which I think means that it gets set before loading the package), or even set the variable before the `use-package` call. I think that made a difference for me.

**Comment by malb** [comment]
No dice, I'm afraid. Move `ob-async` stuff to `:init` and

```
(setq comp-deferred-compilation-black-list '("jupyter-channel"
                                             "ob-async"
                                             "async"
                                             "jupyter"
                                             ))
```
For completeness, even moving `(setq ob-async-no-async-languages-alist '("jupyter-python" "jupyter-julia"))` to the top of the init, doesn't resolve it for me.

**Comment by FelipeLema** [comment]
@malb do mind that `comp-deferred-compilation-black-list` changed to `comp-deferred-compilation-deny-list`

See https://github.com/hlissner/doom-emacs/pull/4309

**Comment by malb** [comment]
Found the issue, closing this.
