### ISSUE TITLE
error in process sentinel: Invalid read syntax: "#"

### ISSUE THREAD

**Issue by bachirelkhadir** [nnicandro/emacs-jupyter#298]
First of all, thank you very much for a terrific package!

I am new to emacs-jupyter, and today after restarting emacs, I started experiencing a weird bug when I run jupyter-python cells from an org file. 

I am using the doom distribution of emacs v27.1 (if that matters). I can connect to a jupyter repl and execute python commands just fine, but I cannot execute source blocks from org files. Here is an example. Consider an org file as simple as this one :

```
#+TITLE: My org file
#+PROPERTY: header-args :session kernel.json

#+BEGIN_SRC jupyter-python
a = 0
#+END_SRC
```

When I open this org file, and execute the first source cell, everything works fine at first. But if  I try to run the same cell again (or any other cell in the org file), I get the following error:

```
executing Jupyter-Python code block...
error in process sentinel: async-handle-result: Invalid read syntax: "#"
error in process sentinel: Invalid read syntax: "#"
```
and the result of the execution (i.e., the line that appears right below the source block when it is executed) looks something like this:
```
#+RESULTS:
: c4ee26de290a00d4c0f96704a44c1475
```

The weird part is that everything worked fine yesterday, and I don't remember doing any changes to my config files. I also tried to reinstall emacs and doom emacs with no success.

 BTW, I load emacs-jupyter as follows:
```
(after! org
  (add-to-list 'org-structure-template-alist
               '("jup" . "src jupyter-python :results raw drawer")))
(use-package jupyter)
(use-package ob-jupyter)
(org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (julia . t)
     (python . t)
     (jupyter . t)))
```

 Any help is very much appreciated, thanks!

**Comment by timlod** [comment]
I've noticed that removing `ob-async` fixes this issue.
However then you won't have async for other cells.

It is strange though since you are using `jupyter-python` without defining `:async` in your header.

**Comment by bachirelkhadir** [comment]
Could you please expand? How did you figure out that ob-async was the problem?

I didn't not install ob-async separately. Does this package come with ob-jupyter by default? Would removing it by hand not break ob-jupyter?

**Comment by timlod** [comment]
That's strange - perhaps there is another issue at play then in your case?
`emacs-jupyter` does not use `ob-async` - if you use both, the former advises to disable the latter for async computation.
In my case, I wanted to use both, but got that error - removing `ob-async` fixed it for me.
If you don't have it installed (perhaps check if it's a dependency of some other thing you have installed?), I am clueless as to what may be going on.

**Comment by bachirelkhadir** [comment]
I see. I just realized that doom emacs comes with emacs-jupyter and ob-async installed by default, so I didn't need to install them separately. Thank you very much for your help!
