### ISSUE TITLE
Emacs 27 json-read: JSON readtable error: 76 

### ISSUE THREAD

**Issue by thriveth** [nnicandro/emacs-jupyter#301]
Trying to move from ob-ipython to emacs-jupyter, I am having trouble getting it to run. 

My main environment that I wish to work from is Anaconda on a Linux machine. 
I do a minimal install of emacs-jupyter with use-package:

```
(use-package emacs-jupyter
  :ensure t
  )
```

Emacs claims it installed jupyter just fine, but when trying to run the REPL, I get the error message:

```
json-read: JSON readtable error: 76 
```

...rather cryptic, I think. I have not een able to find out whether emacs-jupyter finds the Anaconda jupyter kernels and interpreters, but org-babel also does not understand any jupyter-XXX named kernels even though I did

```
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((R . t) 
     (python . t) 
     ;;(ipython . t) 
     (latex . t)
     (ditaa . t)
     (shell . t)
     (jupyter . t)
     ))

  (org-babel-jupyter-override-src-block 'python)
```
...with no luck. 
What am I doing wrong?

**Comment by gmoutso** [comment]
Can you try loading package `jupyter` instead of `emacs-jupyter`? I use the following
```
(use-package jupyter
  :after (ob-jupyter ob-python)
  :config
  (setq jupyter-api-authentication-method 'password)
  (setq jupyter-eval-use-overlays nil)
  (setq org-babel-default-header-args:jupyter-python '((:session . "/jpy:localhost#8888:py")
                                                       (:kernel . "conda-env-edge-py")
                                                       (:async . "yes")
						       (:pandoc t)))
  (add-to-list 'savehist-additional-variables 'jupyter-server-kernel-names)
  (setq ob-async-no-async-languages-alist '("jupyter-python"))
  (add-to-list 'org-structure-template-alist '("j" . "src jupyter-python")))
```

**Comment by thriveth** [comment]
Thanks @gmoutso , I tried basically copying your setup and removing my own, and tried to M-x jupyter-run-repl, but again, I get a "JSON readtable error: 76".

**Comment by gmoutso** [comment]
Can you also load the libraries ob-jupyter and ob-python with use-package or require before you C-c ' the block? 

The "no such language mode" might mean you need
```
(org-babel-do-load-languages
 'org-babel-load-languages
 '( (C . t) (python . t) (emacs-lisp . t) (dot . t) (plantuml . t)
   (jupyter . t)
   ))
```
I don't know why I don't need it (loaded by ob-jupyter?). 

Can you remove the org-babel-default-header-args:jupyter-python line that I wrote above (you would not have a ipykernel called conda-env-edge-py like I have anyway) ?

**Comment by gmoutso** [comment]
Can you run `jupyter kernelspec list --json` on the command line?

**Comment by Jason-S-Ross** [comment]
I had the same issue. Running `jupyter kernelspec list --json` showed a warning message:
```
[ListKernelSpecs] WARNING | Config option `kernel_spec_manager_class` not recognized by `ListKernelSpecs`.
{
  "kernelspecs": {
    "python3": {
      "resource_dir": "/home/jason/anaconda3/share/jupyter/kernels/python3",
      "spec": {
        "argv": [
          "/home/jason/anaconda3/bin/python",
          "-m",
          "ipykernel_launcher",
          "-f",
          "{connection_file}"
        ],
        "env": {},
        "display_name": "Python 3",
        "language": "python",
        "interrupt_mode": "signal",
        "metadata": {}
      }
    }
  }
}
```

It turned out there was a config file `~/anaconda3/etc/jupyter/jupyter_config.json` that had a bad configuration line in it. It's probably a result of a configuration option getting removed in a new version of nb_conda_kernels or something. Getting rid of that line made the warning go away and suddenly I don't get the error 76.

Calling `jupyter kernelspec list --json --log-level=50` in the `jupyter-available-kernelspecs` returns the JSON without the warning message, fyi.

**Comment by thriveth** [comment]
@Jason-S-Ross  The same was the root of my problem, it seems! 

I wonder if this is something that would be worth adding to the documentation? In general, how to set it up with Conda? It's not super hard when one knows how to, but it can be pretty hard to figure out, and especially, this bug was really hard to track down.

**Comment by BuddhiLW** [comment]
I don't know why I have this kind of error, with other packages, also.

For example, org-roam-capture gives me:
`user-error: JSON readtable error: 122.`

Very annoying. That doesn't happen in my laptop, and pretty much it's the same linux and config file distributions. Although both have it's tweaks. Nothing I believe should have to with JSON handling.

I made sure to delete json related packages, indium, and javascript related modes. No success.

**Comment by BuddhiLW** [comment]
It's a little strange, but the problem is the following:

![pic-selected-210620-0700-47](https://user-images.githubusercontent.com/59554283/122669994-186c9180-d196-11eb-8d3e-455d88065ed5.png)

Install jupyter in your system, and guarantee it's usable by your emacs environment.

It's a chain of dependencies breakage.

The solution I found in this thread https://github.com/syl20bnr/spacemacs/issues/9941#

**Comment by darosio** [comment]
I am hitting this after upgrade the system (archlinux) jupyter_client 7.3.1 -> 7.3.2.

**Comment by darosio** [comment]
I confirm jupyter kernel starting correctly with jupyter_client==7.3.3

Thank you very much.
