### ISSUE TITLE
[Regression] Execution indicator [*] does not resolve since update

### ISSUE THREAD

**Issue by timlod** [nnicandro/emacs-jupyter#322]
I updated `emacs-jupyter` yesterday to receive the new updates.
Previously, [\*] would change to [X] (X being a number indicating the nth execution using this kernel) upon completion of execution.
Now, only the output of an execution receives [X], with the input cell perpetually remaining at [\*].

Tested using Emacs 27.1 on different machines, `jupyter 20210404.1745` (MELPA)

**Comment by nnicandro** [comment]
Thanks. Fixed by https://github.com/nnicandro/emacs-jupyter/commit/7735d2b8fb32434992467f0d4d9d59c1a1a5dc0c.
