### ISSUE TITLE
jupyter stuck on requesting kernel info

### ISSUE THREAD

**Issue by cvanelteren** [nnicandro/emacs-jupyter#326]
Hi, I recently switched to `emacs-native-comp` and jupyter-emacs stopped working properly. The only error I can receive from the message buffer is

```
error in process filter: zmq--subprocess-filter: Error in ZMQ subprocess: error, ("Lisp nesting exceeds ‘max-lisp-eval-depth’")
error in process filter: Error in ZMQ subprocess: error, ("Lisp nesting exceeds ‘max-lisp-eval-depth’")
Requesting kernel info...done
jupyter-kernel-info: Kernel did not respond to kernel-info request
```

~~If I manually reinstall jupyter it works but stops working after restart, is there any way to combine this with native-comp?~~

Thanks in advance!

Edit:
`GNU Emacs 28.0.50`

**Comment by cvanelteren** [comment]
After some digging I got some additional output
<details>

  <summary>Debug output</summary>
<code> Requesting kernel info...done
jupyter-kernel-info: Kernel did not respond to kernel-info request
QuitInvalid face reference: highlight-quoted-symbol
Invalid face reference: highlight-quoted-symbol [2 times]
Searched 0/1 files
Searched 1/1 files
Searched 0/1 files
Searched 1/1 files
executing Jupyter-Python code block...
Starting python3 kernel process...done
Channel not started in ioloop subprocess (:shell)
</code>
</details>

**Comment by dileep-kishore** [comment]
Did anybody find a solution for this? I am stuck with the same issue on GNU Emacs 28.0.50
```
Check for compatible module binary to download? (y or n) y
Downloading https://github.com/nnicandro/emacs-zmq/releases/download/v0.10.10/emacs-zmq-x86_64-linux-gnu.tar.gz
Verifying sha256 signature of emacs-zmq-x86_64-linux-gnu.tar.gz
Wrote /home/dileep/.emacs.d/.local/straight/build-28.0.50/zmq/emacs-zmq-x86_64-linux-gnu.tar.gz
Parsing tar file...done
Extracting...done
Loading /home/dileep/.emacs.d/.local/straight/build-28.0.50/zmq/emacs-zmq.so (module)...done
error in process filter: zmq--subprocess-filter: Error in ZMQ subprocess: error, ("Lisp nesting exceeds ‘max-lisp-eval-depth’")
error in process filter: Error in ZMQ subprocess: error, ("Lisp nesting exceeds ‘max-lisp-eval-depth’")
Requesting kernel info...done
```

**Comment by cvanelteren** [comment]
@dileep-kishore  I ended up downgrading tot 27.1.2 which works fine.

**Comment by matteha** [comment]
https://github.com/nnicandro/emacs-jupyter/issues/321 should have fixed it but also getting the error.

**Comment by nnicandro** [comment]
Are you still experiencing issues with `emacs-native-comp`? You can try switching to the `next` branch (WIP) which simplifies a lot of the kernel communication code and may get rid of the error, but it looks like this error has to do with ZMQ subprocesses which are still used.

**Comment by cvanelteren** [comment]
Hi @nnicandro, I believe this problem is gone. I am running 28.0.50 right now without this issue. I have however another weird issue where the kernel dies and then cannot be restored without a proper restart. I haven't been able to track this down but will put another issue up. Closing this one.
