### ISSUE TITLE
`:results drawer :async yes` causes `:end:` to multiply

### ISSUE THREAD

**Issue by veprbl** [nnicandro/emacs-jupyter#328]
Execution of a following cell causes additional `:end:`'s to appear:
```org
#+begin_src jupyter-python :session *mytest* :results drawer :async yes
  print(1)
  1/0
#+end_src

#+RESULTS:
:results:
: 1
:RESULTS:
# [goto error]
: 
: ZeroDivisionErrorTraceback (most recent call last)
: <ipython-input-43-af80a98ca6f3> in <module>
:       1 print(1)
: ----> 2 1/0
: 
: ZeroDivisionError: division by zero
:END:
:end:
:end:
:end:
:end:
:end:
```

**Comment by nnicandro** [comment]
I can confirm this behavior. I suspect this has to do with the outer `:results:` drawer being ended by the first `:END:` so when the drawer is removed from the buffer on the next evaluation there is a leftover `:end:` which remains. I'll look into it. Thanks.

**Comment by veprbl** [comment]
I was just looking at this issue a few minutes ago, as it's an interfering with my workflow. I believe, your explanation for the cause is correct.
I see two potential solutions:
1. To teach `org-babel-result-end` to handle nested drawers (although I'm not even sure if nested blocks are supposed to be allowed in org mode syntax)
2. To not create the nested drawers in the first place.

**Comment by nnicandro** [comment]
The second option seems about right. There shouldn't be a reason to create the nested drawer if one already exists, we should just use the drawer that is already present.

I'm trying to figure out why the nested drawer gets created in the first place. Most likely it has something to do with `jupyter-org--wrap-result-maybe` and related code.

**Comment by veprbl** [comment]
I also wonder if `:` is redundant for inside a drawer. It also prevents syntax highlighting from kicking in:
![image](https://user-images.githubusercontent.com/245573/141705875-26cab909-afbf-45d1-90db-d6efbaff9d39.png)

**Comment by nnicandro** [comment]
Hmmm...the syntax highlighting should work on top of the syntax highlighting of fixed width blocks (lines starting with `:`). At least it does in other cases. For example

```emacs-lisp
#+begin_src jupyter-python :session test
print('AB\x1b[43mCD\x1b[0mEF')
#+end_src
```

I'll have to look into that as well.

**Comment by veprbl** [comment]
That worked like a charm. Thank you very much!
