### ISSUE TITLE
pandas dataframes are truncated in the results block

### ISSUE THREAD

**Issue by yavitzour** [nnicandro/emacs-jupyter#329]
Hi,

Just started using emacs-jupyter and I enjoy it very much. I have one small issue that I'm hoping can be resolved by some configuration that I didn't find. 

When outputting a wide pandas df (with many columns), the output is truncated in the results block at column 75 regardless of the width of the emacs frame.

Can I disable this behavior? Is there a variable that controls the width of the results block?

Example:

#+begin_src jupyter-python :session py :async yes
import pandas as pd
import numpy as np

df = pd.DataFrame(data=[[1,2,3,4,5,6,7,8,9,10,11,12]], columns=["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])
df
#+end_src

#+RESULTS:
:    January  February  March  April  May  June  July  August  September  \\
: 0        1         2      3      4    5     6     7       8          9   
: 
:    October  November  December  
: 0       10        11        12

**Comment by gmoutso** [comment]
I thought it should work out of the box, but anyway can you try the pandoc option below
```
#+begin_src jupyter-python :pandoc 'nil :display plain
pd.DataFrame(data=[[1,2,3,4,5,6,7,8,9,10,11,12]], columns=["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])
#+end_src

#+RESULTS:
:    January  February  March  April  May  June  July  August  September  \
: 0        1         2      3      4    5     6     7       8          9   
: 
:    October  November  December  
: 0       10        11        12  

#+begin_src jupyter-python :pandoc t
pd.DataFrame(data=[[1,2,3,4,5,6,7,8,9,10,11,12]], columns=["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])
#+end_src

#+RESULTS:
:RESULTS:
|     | January   | February   | March   | April   | May   | June   | July   | August   | September   | October   | November   | December   |
|-----+-----------+------------+---------+---------+-------+--------+--------+----------+-------------+-----------+------------+------------|
| 0   | 1         | 2          | 3       | 4       | 5     | 6      | 7      | 8        | 9           | 10        | 11         | 12         |
:END:
```

**Comment by yavitzour** [comment]
Not sure why but for some reason the :pandoc option has no effect on my configuration. I'm still getting the truncated dataframe output. 

The solution I've found for now is to use  [dtale](https://github.com/man-group/dtale) for viewing larger dataframes. I find it very convenient even though it requires opening the dataframe in an external browser window

**Comment by nnicandro** [comment]
The truncated dataframe has to do with pandas display settings. If you run `pd.set_option('display.width', 500)` the truncation disappears. See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.set_option.html.
