### ISSUE TITLE
How to draw the graphics inside a buffer?

### ISSUE THREAD

**Issue by ThomasBucaioni** [nnicandro/emacs-jupyter#331]
Here is my org file:
```
* Test Python jupyter notebook in org-mode

#+BEGIN_SRC jupyter-python :session py
x = 'foo'
y = 'bar'
x + ' ' + y
#+END_SRC

#+RESULTS:
: foo bar

#+BEGIN_SRC jupyter-python :session py :display plain
import pandas as pd
data = [[1, 2], [3, 4]]
pd.DataFrame(data, columns=["Foo", "Bar"])
#+END_SRC

#+RESULTS:
:    Foo  Bar
: 0    1    2
: 1    3    4

#+BEGIN_SRC jupyter-python :session py :file plot.png :results graphics file :async yes
    import numpy as np
    import matplotlib.pyplot as plt
    x=np.linspace(0,6.3,1000)
    plt.plot(x,np.sin(3*x))
    plt.show()
#+END_SRC

#+RESULTS:
[[file:plot.png]]
```
It's certainly not an issue but I didn't know were else to ask... The graphics generates in a file well though, and appears in a new buffer on click

**Comment by gmoutso** [comment]
You could try running it in the scratch buffer or in the repl itself. Bring the hydra up with `C-c h` and try the repl first (press `r` in the hydra), then run the last line `plt.plot(...)`. Also note that `plt.show()` is not needed similarly to a notebook cell run, but you might need to run %matplotlib.

I am also interested in how to get the results of a calculation programmatically, eg put them in a buffer, which I could then parse and do more to them (I am specifically thinking of using %whos in python). I understand that running `(jupyter-eval-string "%whos")` in the org-edit-special might make things easier, but I don't want the pop-up of the results.

**Comment by ThomasBucaioni** [comment]
The hydra answers:
```
org-babel-initiate-session: No org-babel-initiate-session function for nil!
```
But with `%matplotlib` it goes well. Thank you very much

Having the results in a buffer can be very handy, it's a good idea. Pop-ups are a bit invasive for sure (besides, I have a tiling wm and it doesn't make them more convenient...)
