### ISSUE TITLE
[feature request] evaluate string from org-mode source block

### ISSUE THREAD

**Issue by gmoutso** [nnicandro/emacs-jupyter#335]
Can I use jupyter-eval-string from an org-mode file while inside a source block? Can I then use the result to manipulate it in elisp?

    Debugger entered--Lisp error: (wrong-type-argument "Not a valid client" nil jupyter-current-client)

My use case is to send to the kernel the python command `%whos`, which lists variables and their types, have emacs process it and let me do things like insert a known symbol, grep its references in buffer, etc..

**Comment by gmoutso** [comment]
According to #152 I could use the scratch buffer and copy the text from there (programmatically identify the popup buffer and copy it...). Is this the way to go?

**Comment by nnicandro** [comment]
You can use `C-x C-e` to evaluate a line or region of a source block. To bind your own key you can use

```
(jupyter-org-define-key (kbd "C-x C-e") #'jupyter-eval-line-or-region)
```

`jupyter-org-define-key` binds a key to a command ensuring that `jupyter-current-client` is bound to the kernel client of the source block at the point where the command is evaluated.
