### ISSUE TITLE
zeromq error when calling jupyter-eval-buffer

### ISSUE THREAD

**Issue by xzz53** [nnicandro/emacs-jupyter#339]
Hi!

When calling `jupyter-eval-buffer` in a buffer with associated python repl, I get
```
error in process filter: zmq--subprocess-filter: Error in ZMQ subprocess: invalid-read-syntax, ("#")
error in process filter: Error in ZMQ subprocess: invalid-read-syntax, ("#")
```
and repl dies. Neverthless, `jupyter-eval-defun` and `jupyter-eval-region` work fine.

My emacs version is 27.2, emacs-jupyter and emacs-zmq are latest git.

**Comment by nnicandro** [comment]
Can you provide a clean reproduction of the error. For example, starting from an Emacs with just Jupyter loaded and the contents of the buffer you evaluate which causes the invalid read syntax.

**Comment by xzz53** [comment]
> Can you provide a clean reproduction of the error. For example, starting from an Emacs with just Jupyter loaded and the contents of the buffer you evaluate which causes the invalid read syntax.

Well, can't reproduce the issue in a minimal environment. Something must be wrong with my config, I'll try to investigate that. Could you give any hints on debugging?

**Comment by nnicandro** [comment]
If you are able to reproduce the error you may get more information as to its cause by setting `zmq--subprocess-debug` to `t` and examining the stack trace produced. You have to set that variable before connecting to any kernels for it to have an effect.
