### ISSUE TITLE
Blank lines around output

### ISSUE THREAD

**Issue by memeplex** [nnicandro/emacs-jupyter#345]
I get extra whitespace around dataframes in the output:

![image](https://user-images.githubusercontent.com/2845433/137042764-4b7dd151-f9a5-43dc-a9c2-61d6d86baf13.png)

Is it because it's shown as html? Is there any way to make the renderer prefer text over html?

Thanks.

EDIT: just to be clear, I don't mean in an org-babel cell but directly in the REPL, I would like to get rid of that extra space and I'm not sure whether is generated by shr or is just plain text output stuffed with extra space.

**Comment by nnicandro** [comment]
The extra space is due to the HTML rendering using shr as you mentioned. You can change the mime type preference by changing the order of the `jupyter-mime-types` variable.
