### ISSUE TITLE
Doesn't insert newlines when wrapped in `#begin_example`

### ISSUE THREAD

**Issue by NightMachinary** [nnicandro/emacs-jupyter#348]
```elisp
(setq org-babel-min-lines-for-block-output 0)
```

```org
#+begin_src jupyter-python :kernel py_base :session emacs_py_1 :async yes :pandoc t
print(f"Loaded model")
#+end_src

#+RESULTS:
#+begin_exampleLoaded model
#+end_example
```

It should add a newline so that it becomes:
```
#+RESULTS:
#+begin_example
Loaded model
#+end_example
```

**Comment by NightMachinary** [comment]
Actually, working with `emacs-jupyter` more, it completely corrupts the buffer when used with `#begin_example` blocks; It will start to put the next source blocks inside its `:RESULTS:` drawer!

**Comment by nnicandro** [comment]
I'm getting the correct behavior for the example code block you gave in an Emacs session with just `jupyter` and its dependencies loaded. Not sure what could be going wrong in your case. Is it possible that there are packages you use that are interefering with Jupyter?

Could you try loading just Jupyter and its dependencies and see if your example gives the correct results to rule that out? If you installed this package by cloning the repo, you can run `make init` (after installing [Cask](https://github.com/cask/cask)) in the root directory and then execute the following bash script

```bash
export EMACSLOADPATH=$(cask load-path)
emacs -Q --eval "(require 'jupyter)" --eval "(setq org-babel-load-languages (quote ((python . t) (jupyter . t))))" --eval "(setq org-confirm-babel-evaluate nil)"
```

Then you can create an Org buffer in the launced Emacs session and try your example.

Can you give an example which results in a corrupted buffer?

**Comment by NightMachinary** [comment]
@nnicandro I have since disabled using `#+begin_example` with `jupyter` blocks, and now I still have some issues with folding (sometimes `#+RESULTS:` gets folded to `...` while the rest of the results are not folded, and the only way to unfold it is to cancer all folds in the current buffer), but I suspect these folding issues are indeed courtesy of Doom, not `emacs-jupyter`. 

As you have not been able to repro this, I will close the issue, as the odds of this issue becoming a huge time sink of trying to find the offending bit of code has now increased exponentially. If other people should be able to reproduce the bug, I will try to reproduce the bug on `emacs -q` also, but as it's currently just myself, I prefer to just live with it. Thanks.

**Comment by nnicandro** [comment]
My guess is it has something to do with `jupyter-org--insert-result` and related functions. Thinking about it though, I don't know how there could be a missing newline since only [Org element](https://orgmode.org/worg/dev/org-element-api.html) data structures are manipulated internally. Those get turned into their string representations at the moment of insertion with `org-element-interpret-data`. `emacs-jupyter` just inserts those string representations, with some exceptions for stream (standard output) messages.
