### ISSUE TITLE
where is the order of outputs determined?

### ISSUE THREAD

**Issue by jkitchin** [nnicandro/emacs-jupyter#351]
In this block:

```
#+BEGIN_SRC jupyter-python
from IPython.display import HTML, Markdown, Latex

print(1)
display(HTML('<b>bold</b>'),
        Latex('\\bf{lbold}'),
        Markdown('**mbold**'))
print(2)
#+END_SRC
```

I would expect this output:

```
: 1
*bold*
*lbold*
*mbold*
: 2
```

but I get this:

```
1
2
*mbold*
*lbold*
*bold*
```

I have gathered that display output is always last, and that seems to be how it comes from the request. I can't find where that happens though. Any hints?

**Comment by nnicandro** [comment]
Hello,

The order of outputs is determined by the order in which the messages are received from the kernel. A message is received by a process filter function which calls `jupyter-event-handler` which in turn calls `jupyter-handle-message` defined in `jupyter-client.el`. `jupyter-handle-message` is responsible for calling the particular client message handlers that do the inserting, i.e. the `jupyter-handle-*` methods in `jupyter-org-client.el`. Hope that helps.

I ran your code and I get the expected output, at least communicating directly with a local kernel through ZMQ sockets. Could it be that the order of message reception gets scrambled in transit? But I guess in that case there wouldn't be a completely fixed output order.

**Comment by jkitchin** [comment]
huh. I am pretty sure I am using a local kernel, and zmq via emacs-jupyter, via a src block in org-mode. In the repl, I get the order expected.

![image](https://user-images.githubusercontent.com/1610070/139741098-22e2278f-efba-4dbe-833d-b8deccf1bbab.png)

In org-mode I get (and it seems to always be the same, that displayed things come last)

![image](https://user-images.githubusercontent.com/1610070/139741164-703e9812-a40f-44bd-ac76-72992564add7.png)

Do you get the same order in both places?

 I had the impression from https://github.com/nnicandro/emacs-jupyter#standard-output-displayed-data-and-code-block-results that display code is always put last

**Comment by nnicandro** [comment]
Yes I get the same order in both places even with an `emacs -Q` session loading only `jupyter` and its dependencies. Although the results I get look different in Org. The drawer looks like

```
:RESULTS:
: 1
#+begin_export html
<b>bold</b>
#+end_export
#+begin_export latex
\bf{lbold}
#+end_export
#+begin_export markdown
**mbold**
#+end_export
: 
: 2
:END:
```

Could there be some interaction between the Jupyter package and the other packages you are using?

Thanks for catching the ambiguity in that section of the README. Plenty of other sections like that, I'm sure. It should say something more along the lines of: messages that have something that can be inserted into a buffer are inserted in the order they arrive in. I think I was trying to say that with the `appended to a :RESULTS: drawer` bit.

**Comment by jkitchin** [comment]
I see what is happening. it is from using :pandoc t in the header (I have this set as a default). With the vanilla settings I see:

![image](https://user-images.githubusercontent.com/1610070/139868259-e6bb7de6-3aa9-48bd-8546-971ea3860714.png)

but with :pandoc t

![image](https://user-images.githubusercontent.com/1610070/139868337-a9a8b52d-d8c9-4240-83be-2fcf53b3f7a3.png)

that seems like a bug to me.

**Comment by nnicandro** [comment]
I can confirm that using `:pandoc t` results in the wrong output order. It does seem to be a bug. I'll look into it. Thanks.

**Comment by jkitchin** [comment]
I wonder if the problem is the amount of time it takes to convert with pandoc. If I override `jupyter-org-export-block-or-pandoc` (which does nothing obvious to the order) like this, then I get the right order. However, if I put a time delay, it moves things to the end.

```
(defun scimax-jupyter-org-export-block-or-pandoc (type value params)
  "Return VALUE, either converted with pandoc or in an export block.
If PARAMS has non-nil value for key ':pandoc' and TYPE is in
`jupyter-org-pandoc-convertable', convert the result with pandoc.
Otherwise, wrap it in an export block."
  (jupyter-org-export-block type value))

(advice-add 'jupyter-org-export-block-or-pandoc :override 'scimax-jupyter-org-export-block-or-pandoc)
```

One possible solution is to do the pandoc transform later, after the results order is fixed. That is only partly correct though, and relies on the order  through the filter. I guess any result that takes a long time could mess up the order this way. It seems like this happens after the request comes back though, so it is an elisp implementation detail right?

**Comment by jkitchin** [comment]
> I can confirm that using `:pandoc t` results in the wrong output order. It does seem to be a bug. I'll look into it. Thanks.

I think it is a "feature" based on the note above.

**Comment by nnicandro** [comment]
Oh yes it has to do with the delay caused by the pandoc transformation. If a message comes in during that time it gets handled before the transformation completes just by the way process filters work. It's more like any result which allows the process filters to run.

There would be issues with asynchronous output if the pandoc transformation is delayed until after the cell is completed (or when the results order is fixed) I think.

Maybe a temporary string can be displayed, like `Converting...`, to act as a placeholder while the conversion is taking place. For each result which requires conversion, that string is displayed with a corresponding text property distinguishing it from other results being converted. Once conversion is done for a result that text property is searched for and the string replaced with the converted result. This seems to be another possible route. This would introduce a period of time where the results displayed in the buffer are not the same as what the kernel sent though.

**Comment by nnicandro** [comment]
Instead of using text properties, overlays can be used. Just insert the non-converted result, overlay it with a `Converting...` string, and then replace the non-converted result with the converted one once complete.

**Comment by jkitchin** [comment]
I don't have a strong opinion on which way, it seems that overlays can be a problem if there are a lot of them, and you don't take care to delete them. I would probably lean towards text properties as a result.

Depending on the content though, you would want to ensure it was not font-locked. e.g. one reason to use pandoc is to avoid a long html block getting dumped in emacs, and then slowing it down as font-lock tries to fontify it. If that can be avoided with a display string, not problem!

**Comment by nnicandro** [comment]
I came up with a solution in #358. Could you let me know if it solves your problem. Feedback is also appreciated.
