### ISSUE TITLE
tab-always-indent, auto complete side-effects on new line

### ISSUE THREAD

**Issue by pati-ni** [nnicandro/emacs-jupyter#367]
I've had this `(setq tab-always-indent 'complete)`  present in my configuration.

From the emacs manual:

> If ‘complete’, TAB first tries to indent the current line, and if the line
> was already indented, then try to complete the thing at point.

When I was pressing enter to enter a new line I was getting the whole source block frozen.

### The problem (pressing new line)

![2021-12-06_12:43:15-emacs](https://user-images.githubusercontent.com/14965608/144848462-daa49494-d33f-4b42-8435-2acb3bbdcb19.png)

Setting `(setq tab-always-indent t)` mitigates the issue.

Is this the intended behavior?

**Comment by timlod** [comment]
This happens when you use selectrum's in-buffer completion (`(setq selectrum-complete-in-buffer t)`) [AFAIK it has nothing to do with `emacs-jupyter`]
Essentially, selectrum tries to complete on TAB, and on `org-new-line`, eventually a TAB is triggered for indentation purposes.

I wrote an advice to combine the two you may want to use:
```elisp
(defun selectrum-only-with-prompt (orig-fun start end collection predicate)
    (let ((check))
      (setq check (or (= ?  (preceding-char)) (= ?\C-j (preceding-char))))
      (setq check (or check (= 0 (preceding-char))))
      (unless check
        (apply orig-fun (list start end collection predicate)))))
(advice-add 'selectrum-completion-in-region :around
            #'selectrum-only-with-prompt))
```

This will only try completion when there is a symbol in front of the cursor to complete, hence you won't get popups on newlines anymore.

**Comment by pati-ni** [comment]
Thanks for the reply and the proposed solution @timlod . Unfortunately, I do not have selenium installed in my emacs.

These are the active `completion-styles`
```
completion-styles
(basic partial-completion emacs22)
```

So, it looks like that something else may be causing the same effect. I will dig into it a bit more

**Comment by timlod** [comment]
Oh, indeed I see you're using `ivy`, not `selectrum`. I suppose the same might work for the equivalent function in `ivy` though.
If a function like `ivy-completion-in-region` or similar exists that is being called (you could find out ie. by profiling or stepping into `newline`), you should be able to use a similar advice to fix this for yourself. There may also exist a parameter to turn the completion off like in selectrum.
