### ISSUE TITLE
jupyter-python colored error result not rendered properly 

### ISSUE THREAD

**Issue by Inc0n** [nnicandro/emacs-jupyter#368]
It all works fine jupyter repl:
<img width="591" alt="Screenshot 2021-12-07 at 18 16 38" src="https://user-images.githubusercontent.com/33980911/145084261-c0a8ba41-a20f-4171-9019-0689a9964894.png">
 
However, in org src block:
<img width="1040" alt="Screenshot 2021-12-07 at 18 12 56" src="https://user-images.githubusercontent.com/33980911/145084349-d22b4d8f-e292-47a7-b23c-24a8b359958c.png">

It looks like this, I played around with `:display text/plain` with no luck.

Note: The two images are output of different snippet of code.

**Comment by timlod** [comment]
https://github.com/nnicandro/emacs-jupyter/issues/366
