### ISSUE TITLE
`jupyter-run-repl` starts wrong kernel when called interactively

### ISSUE THREAD

**Issue by xor-xor** [nnicandro/emacs-jupyter#371]
Let's say that we have two kernels: `numpy_tmp` and `tmp`. If we'll call `jupyter-run-repl` interactively with an intention to run `tmp`, we'll actually get `numpy_tmp` instead - and this happens despite the fact that `jupyter-completing-read-kernelspec` returns an exact name (`tmp`), so there's no ambiguity here (which, in contrast, needs to be resolved in case of non-interactive calls).

Basically, this issue seems to be an easy one to solve, as it boils down to the use of `jupyter-find-kernelspecs` function. It appears in `jupyter-run-repl` first, but is skipped when `jupyter-run-repl` is called interactively, which totally makes sense. Then it appears again, deeper down in `jupyter-start-new-kernel`, wrapped in `jupyter-guess-kernelspec`, but this time it is not guarded by `called-interactively-p` - and this is precisely where this bug comes from.

One may think: "ok, so let's just change this second call from `jupyter-guess-kernelspec` to `jupyter-get-kernelspec`, as we have an exact name, so there's no need for guessing" - but doing this will probably break things if someone is relying on the behavior described in `jupyter-start-new-kernel`'s docstring:

> KERNEL-NAME is the name of the kernel to start.  **It can also be the prefix of a valid kernel name, in which case the first kernel in `jupyter-available-kernelspecs' that has KERNEL-NAME as a prefix will be used**. 

Any thoughts on how to proceed here?

EDIT: on the other hand, `jupyter-run-repl` may be simply changed to require an exact name of an existing kernel and signal an error otherwise, but then again, it may break things if someone is relying on this behavior:

> Run a Jupyter REPL connected to a kernel with name, KERNEL-NAME. **KERNEL-NAME will be passed to `jupyter-find-kernelspecs' and the first kernel found will be used to start the new kernel**.

**Comment by xor-xor** [comment]
So in general, what kind of problem this return-the-first-one-found approach is supposed to solve? Why such ambiguity is allowed, instead of just requiring an exact name?

**Comment by nnicandro** [comment]
I'm not entirely sure why I did the return-the-first-one-found approach. I think it boiled down to being able to specify just `python` to get the `python3` and `julia` to get a `julia-X.Y` kernel.

Maybe the route is to instead have the `KERNEL-NAME` argument in `jupyter-run-repl` be a regular expression and wrap it in `^$` when `jupyter-run-repl` is called interactively since the name is exact anyways. In the non-interactive case you can specify the regular expression to be as strict as you want. Doing it this way, there would be no issues with any current user's workflow. WDYT?

**Comment by xor-xor** [comment]
Yeah, it makes sense. I'm playing with this idea right now, so I'll submit a PR soon (adding a test or two would be good for this one, I guess).

BTW, I've just discovered that this return-the-first-one-found approach works only by coincidence, i.e. is non-deterministic. That's because the kernelspecs returned from `jupyter kernelspec list --json` have no intrinsic ordering, in contrast to the output of `jupyter kernelspec list`, which is sorted alphabetically, by names. But that's easy to fix.
