### ISSUE TITLE
How can I send my output to the REPL

### ISSUE THREAD

**Issue by nicolasshu** [nnicandro/emacs-jupyter#403]
I start by opening a python file, and then run a REPL:

```
M-x jupyter-run-repl
```
and then a nice REPL shows up:
![image](https://user-images.githubusercontent.com/12994607/177885175-2c234ee8-17cb-4da2-9794-cce1c314cf78.png)

Now, I run `M-x jupyter-repl-associate-buffer` in order to associate my Python file buffer with the REPL that I have just opened:
![image](https://user-images.githubusercontent.com/12994607/177885331-49f16201-ad19-4105-801f-d5b41d0ea50d.png)

At this point, I start to try to evaluate parts of the code, and on the echo area / minibuffer, it shows that the code has been evaluated: 
![image](https://user-images.githubusercontent.com/12994607/177885475-4cd847e0-8bd5-465b-9148-1a508f986174.png)

When I try to show some of the variables, it shows on the echo area
![image](https://user-images.githubusercontent.com/12994607/177885566-2492a48d-daba-432c-9825-93d22c250311.png)

But when I print it or I show a plot, it opens a new buffer called `*jupyter-output*` as follows:
![image](https://user-images.githubusercontent.com/12994607/177885657-fecf7024-d2ba-4904-b579-654abb0309f9.png)
![image](https://user-images.githubusercontent.com/12994607/177885694-f20a95df-20d4-4b97-88ac-4d2f36560ca8.png)

If I show Pandas dataframes it shows on the echo area as expected:
![image](https://user-images.githubusercontent.com/12994607/177885771-beb64c58-a08b-4115-937d-800a2908bedf.png)

However, is there a way to put show the output on the REPL buffer and to show the code that it was just evaluated?
![image](https://user-images.githubusercontent.com/12994607/177885861-d6b7396c-2cc3-4700-8a7d-a6f3c2e76bc6.png)

Thank you very much!

**Comment by ganesh-krishnan** [comment]
Set ` jupyter-repl-echo-eval-p` to `t`: `(setq jupyter-repl-echo-eval-p t)`

**Comment by nicolasshu** [comment]
@ganesh-krishnan, I love you. Thank you
