### ISSUE TITLE
Progressbars like tqdm are not working

### ISSUE THREAD

**Issue by weidtn** [nnicandro/emacs-jupyter#406]
Hello,

is it possible to have tqdm progressbars working? Right now it just prints the start and does not fill.

```
#+begin_src jupyter-python :session tqdm :async yes
from tqdm.auto import trange
import time

for i in trange(int(1e4)):
    pass

print("done")
#+end_src

#+RESULTS:
:   0%|          | 0/10000 [00:00<?, ?it/s]done
```

**Comment by weidtn** [comment]
I did update my packages and doom itself, now it works. Sorry!

**Comment by colormotor** [comment]
This seems to be broken again now with the latest version of doom. Do you have specific ideas on what the problem depends on?
